version: "3.7"
networks:
  my-network:
    driver: bridge

services: 
  nginx:
    image: nginx:1.19
    ports: 
      - 8082:80
    volumes: 
      - ./src/:/var/www/myapp
      - ./conf/docker/nginx/:/etc/nginx/conf.d/
    working_dir: /var/www/myapp    
    networks: 
      - my-network

  php:
    build:
      context: ./docker/phpfpm
      dockerfile: 7.3-Dockerfile
    volumes: 
      - ./src/:/var/www/myapp
    container_name: Todolist2
    working_dir: /var/www/myapp 
    networks: 
      - my-network

  mariadb:
    image: mariadb:10.3.28-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_todolist
    ports:
      - "3306:3306"
    networks:
      - my-network